spring:
  application:
    name: amoy-gateway
  cloud:
    gateway:
      routes:
        - id: admin_hello
          uri: http://127.0.0.1:21188/
          predicates:
            - Path=/cb02fef92bac/**
        - id: simple_hello
          uri: http://127.0.0.1:8081/
          predicates:
            - Path=/amoy/**
        - id: lottery
          uri: http://127.0.0.1:11100/
          predicates:
            - Path=/lottery/**
        - id: qq_route
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
